import { readFile } from 'node:fs/promises';
import { CORPUS_PATH } from '../lib/config.js';
import type { GeneratedProspect } from '../lib/engine-bridge.js';
import {
  newEvalCtx,
  draftOneClass,
  group,
  GROUP_ORDER,
  mean,
  stdev,
  gradeOf,
} from './class-build.js';
import type { Corpus, DraftPickRecord } from '../lib/types.js';

/**
 * Truth Arbiter — first check: physical & athletic realism by position group.
 *
 * Compares the distribution of every measurable/combine metric for a freshly
 * generated GMSim "drafted class" against 13 years of real drafted players.
 * This directly validates the engine's position baselines (the size +
 * combine norms in draft/measurables.ts) against reality, and flags any
 * position/metric where we're off by more than half a real standard
 * deviation — the gaps worth tuning for NFL feel.
 *
 * Usage: pnpm --filter @gmsim/truth-arbiter run arbiter
 */

interface Metric {
  label: string;
  real: (p: DraftPickRecord) => number | null;
  gen: (g: GeneratedProspect) => number | null;
  /** Lower is better (40, cone, shuttle) — affects how we phrase the gap. */
  lowerBetter?: boolean;
}

const METRICS: Metric[] = [
  { label: 'height(in)', real: (p) => p.measurables.heightInches, gen: (g) => g.measurables.heightInches },
  { label: 'weight(lb)', real: (p) => p.measurables.weightLbs, gen: (g) => g.measurables.weightLbs },
  { label: 'arm(in)', real: (p) => p.measurables.armInches, gen: (g) => g.measurables.armLengthInches },
  { label: '40(s)', real: (p) => p.combine?.forty ?? null, gen: (g) => g.measurables.fortyYardSeconds, lowerBetter: true },
  { label: 'bench', real: (p) => p.combine?.bench ?? null, gen: (g) => g.measurables.benchPress225Reps },
  { label: 'vert(in)', real: (p) => p.combine?.vertical ?? null, gen: (g) => g.measurables.verticalInches },
  { label: 'broad(in)', real: (p) => p.combine?.broadJump ?? null, gen: (g) => g.measurables.broadJumpInches },
  { label: '3cone(s)', real: (p) => p.combine?.cone ?? null, gen: (g) => g.measurables.threeConeSeconds, lowerBetter: true },
  { label: 'shuttle(s)', real: (p) => p.combine?.shuttle ?? null, gen: (g) => g.measurables.shuttleSeconds, lowerBetter: true },
];

const FLAG_SIGMA = 0.5; // |Δ| beyond this many real-σ gets flagged

interface Row {
  groupName: string;
  metric: string;
  realMean: number;
  realSd: number;
  realN: number;
  genMean: number;
  genSd: number;
  genN: number;
  delta: number;
  deltaSigma: number;
}

async function main(): Promise<void> {
  const corpus = JSON.parse(await readFile(CORPUS_PATH, 'utf8')) as Corpus;
  const real = corpus.picks;

  // Draft from each pool's GRADUATING COHORT (SR/RS_SR ≈ 285 ≈ one real
  // draft), not the cream of many pooled classes — so the bottom of the
  // class is a genuinely marginal prospect, reproducing the real talent
  // gradient. Draft value = projected grade (key-skill ceilings) × position
  // value (QB/EDGE/CB premium), mirroring how real boards rank prospects.
  const thresholds = roundShareThresholds(real);
  const DRAFT_SIZE = Math.round(real.length / corpus.years.length); // ≈ one draft
  const seeds = ['arb-0', 'arb-1', 'arb-2', 'arb-3', 'arb-4', 'arb-5'];

  const ctx = newEvalCtx();
  const grade = (g: GeneratedProspect): number => gradeOf(g, ctx);

  // Pool several independent classes (each a single graduating cohort) for a
  // stable aggregate sample; round assigned by rank within each class.
  const drafted: GeneratedProspect[] = [];
  const genRound = new Map<GeneratedProspect, number>();
  for (const seed of seeds) {
    const cls = await draftOneClass(seed, ctx, DRAFT_SIZE);
    cls.forEach((g, i) => {
      genRound.set(g, roundForFraction(i / cls.length, thresholds));
      drafted.push(g);
    });
  }

  // Bucket real + generated by position group.
  const realByGroup = new Map<string, DraftPickRecord[]>();
  for (const p of real) {
    const grp = group(p.position);
    if (grp) (realByGroup.get(grp) ?? realByGroup.set(grp, []).get(grp)!).push(p);
  }
  const genByGroup = new Map<string, GeneratedProspect[]>();
  for (const g of drafted) {
    const grp = group(g.nflProjectedPosition);
    if (grp) (genByGroup.get(grp) ?? genByGroup.set(grp, []).get(grp)!).push(g);
  }

  const rows: Row[] = [];
  for (const grp of GROUP_ORDER) {
    const rs = realByGroup.get(grp) ?? [];
    const gs = genByGroup.get(grp) ?? [];
    for (const metric of METRICS) {
      const rv = rs.map(metric.real).filter((x): x is number => x !== null);
      const gv = gs.map(metric.gen).filter((x): x is number => x !== null);
      if (rv.length < 5 || gv.length < 5) continue;
      const realMean = mean(rv);
      const realSd = stdev(rv);
      const genMean = mean(gv);
      const delta = genMean - realMean;
      rows.push({
        groupName: grp,
        metric: metric.label,
        realMean,
        realSd,
        realN: rv.length,
        genMean,
        genSd: stdev(gv),
        genN: gv.length,
        delta,
        deltaSigma: realSd > 0 ? delta / realSd : 0,
      });
    }
  }

  printReport(rows, real.length, drafted.length);
  printPositional(real, drafted);
  printGradeByRound(real, drafted, genRound, grade);
}

/** Cumulative pick-share thresholds per round (1..7) from the real corpus —
 *  e.g. R1 ≈ 0.125 of picks. Used to assign a generated draft's rounds by
 *  rank fraction, matching the real round-size structure. */
function roundShareThresholds(real: DraftPickRecord[]): number[] {
  const counts: Record<number, number> = {};
  let total = 0;
  for (const p of real) {
    if (p.round >= 1 && p.round <= 7) {
      counts[p.round] = (counts[p.round] ?? 0) + 1;
      total++;
    }
  }
  const cum: number[] = [];
  let running = 0;
  for (let r = 1; r <= 7; r++) {
    running += (counts[r] ?? 0) / total;
    cum[r] = running;
  }
  return cum;
}

function roundForFraction(f: number, cum: number[]): number {
  for (let r = 1; r <= 7; r++) {
    if (f < (cum[r] ?? 1)) return r;
  }
  return 7;
}

/** Check 2a — positional supply: share of the drafted class at each group. */
function printPositional(real: DraftPickRecord[], drafted: GeneratedProspect[]): void {
  const realCount = new Map<string, number>();
  const genCount = new Map<string, number>();
  let rTot = 0;
  let gTot = 0;
  for (const p of real) {
    const grp = group(p.position);
    if (grp) {
      realCount.set(grp, (realCount.get(grp) ?? 0) + 1);
      rTot++;
    }
  }
  for (const g of drafted) {
    const grp = group(g.nflProjectedPosition);
    if (grp) {
      genCount.set(grp, (genCount.get(grp) ?? 0) + 1);
      gTot++;
    }
  }
  console.log(`\n=== positional supply — share of drafted class ===`);
  console.log(`    ${'group'.padEnd(6)} ${'real%'.padStart(7)} ${'gen%'.padStart(7)} ${'Δpp'.padStart(7)}`);
  for (const grp of GROUP_ORDER) {
    const rPct = ((realCount.get(grp) ?? 0) / rTot) * 100;
    const gPct = ((genCount.get(grp) ?? 0) / gTot) * 100;
    const d = gPct - rPct;
    const flag = Math.abs(d) >= 3 ? `  <-- ${d > 0 ? 'OVER' : 'UNDER'}-supplied` : '';
    console.log(`    ${grp.padEnd(6)} ${rPct.toFixed(1).padStart(7)} ${gPct.toFixed(1).padStart(7)} ${d.toFixed(1).padStart(7)}${flag}`);
  }
}

/** Check 2b — talent/grade curve by round: do we separate elite from late
 *  the way real classes do? Real uses NGS Overall, generated uses talent
 *  (mean skills); scales differ, so we compare the % decline from round 1. */
function printGradeByRound(
  real: DraftPickRecord[],
  drafted: GeneratedProspect[],
  genRound: Map<GeneratedProspect, number>,
  grade: (g: GeneratedProspect) => number,
): void {
  const realByRound = new Map<number, number[]>();
  for (const p of real) {
    if (p.scores.overall !== null) {
      (realByRound.get(p.round) ?? realByRound.set(p.round, []).get(p.round)!).push(p.scores.overall);
    }
  }
  const genByRound = new Map<number, number[]>();
  for (const g of drafted) {
    const r = genRound.get(g)!;
    (genByRound.get(r) ?? genByRound.set(r, []).get(r)!).push(grade(g));
  }

  const realR1 = realByRound.get(1)?.length ? mean(realByRound.get(1)!) : 0;
  const genR1 = genByRound.get(1)?.length ? mean(genByRound.get(1)!) : 0;

  console.log(`\n=== talent/grade curve by round (decline from R1) ===`);
  console.log(`    ${'rnd'.padEnd(4)} ${'real(NGS)'.padStart(10)} ${'rΔ%'.padStart(7)} ${'gen(tal)'.padStart(10)} ${'gΔ%'.padStart(7)}`);
  for (let r = 1; r <= 7; r++) {
    const rv = realByRound.get(r) ?? [];
    const gv = genByRound.get(r) ?? [];
    if (rv.length === 0 || gv.length === 0) continue;
    const rm = mean(rv);
    const gm = mean(gv);
    const rDrop = realR1 ? ((rm - realR1) / realR1) * 100 : 0;
    const gDrop = genR1 ? ((gm - genR1) / genR1) * 100 : 0;
    const flag = Math.abs(gDrop - rDrop) >= 4 ? `  <-- ${Math.abs(gDrop) < Math.abs(rDrop) ? 'too FLAT' : 'too STEEP'}` : '';
    console.log(
      `    R${String(r).padEnd(3)} ${rm.toFixed(1).padStart(10)} ${rDrop.toFixed(1).padStart(7)} ${gm.toFixed(1).padStart(10)} ${gDrop.toFixed(1).padStart(7)}${flag}`,
    );
  }
}

function fmt(n: number, d = 1): string {
  return n.toFixed(d).padStart(7);
}

function printReport(rows: Row[], realN: number, genN: number): void {
  console.log(`\n=== TRUTH ARBITER — physical/athletic realism by position ===`);
  console.log(`real drafted: ${realN} (2014-2026)   generated class: ${genN} (top-by-talent)\n`);

  let curGroup = '';
  for (const r of rows) {
    if (r.groupName !== curGroup) {
      curGroup = r.groupName;
      console.log(`\n  ${curGroup}`);
      console.log(
        `    ${'metric'.padEnd(11)} ${'real μ±σ'.padStart(16)} ${'gen μ±σ'.padStart(16)} ${'Δ'.padStart(8)} ${'Δσ'.padStart(7)}`,
      );
    }
    const flag = Math.abs(r.deltaSigma) >= FLAG_SIGMA ? '  <-- ' + (r.delta > 0 ? 'HIGH' : 'LOW') : '';
    console.log(
      `    ${r.metric.padEnd(11)} ${(`${r.realMean.toFixed(1)}±${r.realSd.toFixed(1)}`).padStart(16)} ` +
        `${(`${r.genMean.toFixed(1)}±${r.genSd.toFixed(1)}`).padStart(16)} ${fmt(r.delta)} ${fmt(r.deltaSigma, 2)}${flag}`,
    );
  }

  // Biggest divergences across everything.
  const worst = [...rows].sort((a, b) => Math.abs(b.deltaSigma) - Math.abs(a.deltaSigma)).slice(0, 12);
  console.log(`\n=== biggest divergences (|Δσ|) ===`);
  for (const r of worst) {
    console.log(
      `  ${(`${r.groupName} ${r.metric}`).padEnd(20)} real ${r.realMean.toFixed(1)}  gen ${r.genMean.toFixed(1)}  Δσ ${r.deltaSigma.toFixed(2)}`,
    );
  }
  const flagged = rows.filter((r) => Math.abs(r.deltaSigma) >= FLAG_SIGMA).length;
  console.log(`\n${flagged}/${rows.length} (group × metric) cells diverge by ≥${FLAG_SIGMA}σ.\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
