import { describe, it, expect } from 'vitest';
import { createLeague } from '../league/generate.js';
import { simulateSeason } from './runner.js';
import { advanceSeason } from './advance.js';
import { seasonAwards } from './awards.js';
import type { LeagueState } from '../types/league.js';

function runSeasons(seed: string, n: number): LeagueState {
  let league = createLeague({ seed });
  for (let i = 0; i < n; i++) {
    league = simulateSeason(league);
    league = advanceSeason(league);
  }
  return league;
}

describe('career awards snapshot', () => {
  it('every fresh league player + coach starts with empty careerAwards', () => {
    const league = createLeague({ seed: 'caw-fresh' });
    for (const p of Object.values(league.players)) {
      expect(p.careerAwards).toEqual([]);
    }
    for (const c of Object.values(league.coaches)) {
      expect(c.careerAwards).toEqual([]);
    }
  });

  it('MVP winner gains an MVP entry tagged with the season just played', () => {
    const played = simulateSeason(createLeague({ seed: 'caw-mvp' }));
    const awards = seasonAwards(played);
    const mvpId = awards.mvp!.playerId;
    const after = advanceSeason(played);
    const mvp = after.players[mvpId];
    expect(mvp).toBeDefined();
    const mvpEntries = mvp!.careerAwards.filter((a) => a.kind === 'MVP');
    expect(mvpEntries.length).toBe(1);
    expect(mvpEntries[0]!.seasonNumber).toBe(played.seasonNumber);
  });

  it('COY winner appears on the head coach record, not the players', () => {
    const played = simulateSeason(createLeague({ seed: 'caw-coy' }));
    const awards = seasonAwards(played);
    const coachId = awards.coy!.coachId;
    const after = advanceSeason(played);
    const coach = after.coaches[coachId]!;
    const coyEntries = coach.careerAwards.filter((a) => a.kind === 'COY');
    expect(coyEntries.length).toBe(1);
    expect(coyEntries[0]!.seasonNumber).toBe(played.seasonNumber);

    // No player should have a COY entry.
    for (const p of Object.values(after.players)) {
      expect(p.careerAwards.find((a) => a.kind === 'COY')).toBeUndefined();
    }
  });

  it('multi-season awards accumulate without duplicates per season', () => {
    const league = runSeasons('caw-multi', 5);
    for (const p of Object.values(league.players)) {
      const seenSeasons = new Set<string>();
      for (const a of p.careerAwards) {
        const key = `${a.kind}:${a.seasonNumber}`;
        expect(seenSeasons.has(key)).toBe(false);
        seenSeasons.add(key);
      }
    }
  });

  it('award counts league-wide are at most one per season per category', () => {
    const seasons = 4;
    const league = runSeasons('caw-counts', seasons);

    const playerCounts: Record<string, number> = { MVP: 0, OPOY: 0, DPOY: 0, OROY: 0, DROY: 0 };
    for (const p of Object.values(league.players)) {
      for (const a of p.careerAwards) {
        playerCounts[a.kind] = (playerCounts[a.kind] ?? 0) + 1;
      }
    }
    // Every season produces exactly one of each player award. The total
    // *active* count can only be lower than `seasons` if a winner has
    // retired (Phase 2 drops retiree career history). Allow a small
    // shortfall — if a category falls more than 1 short across 4
    // seasons we'd want to investigate.
    for (const kind of ['MVP', 'OPOY', 'DPOY', 'OROY', 'DROY'] as const) {
      expect(playerCounts[kind]).toBeLessThanOrEqual(seasons);
      expect(playerCounts[kind]).toBeGreaterThanOrEqual(seasons - 1);
    }

    // COY accrues to a head coach, which doesn't retire in Phase 2,
    // so the strict equality still holds.
    let coyTotal = 0;
    for (const c of Object.values(league.coaches)) {
      coyTotal += c.careerAwards.filter((a) => a.kind === 'COY').length;
    }
    expect(coyTotal).toBe(seasons);
  });

  it('rookies generated by retirement start with empty careerAwards', () => {
    const played = simulateSeason(createLeague({ seed: 'caw-rookie' }));
    const beforeIds = new Set(Object.keys(played.players));
    const after = advanceSeason(played);
    const newIds = Object.keys(after.players).filter((id) => !beforeIds.has(id));
    for (const id of newIds) {
      expect(after.players[id]!.careerAwards).toEqual([]);
    }
  });

  it('determinism — same seed yields identical careerAwards arrays', () => {
    const a = runSeasons('caw-det', 3);
    const b = runSeasons('caw-det', 3);
    for (const id of Object.keys(a.players)) {
      expect(b.players[id]!.careerAwards).toEqual(a.players[id]!.careerAwards);
    }
    for (const id of Object.keys(a.coaches)) {
      expect(b.coaches[id]!.careerAwards).toEqual(a.coaches[id]!.careerAwards);
    }
  });
});
