import { describe, it, expect } from 'vitest';
import { createLeague } from '../league/generate.js';
import { simulateSeason } from './runner.js';
import { advanceSeason } from './advance.js';
import { seasonStatsForLeague } from './stats.js';
import { Position } from '../types/enums.js';
import type { LeagueState } from '../types/league.js';

function runSeasons(seed: string, n: number): LeagueState {
  let league = createLeague({ seed });
  for (let i = 0; i < n; i++) {
    league = simulateSeason(league);
    league = advanceSeason(league);
  }
  return league;
}

describe('career stats accumulation', () => {
  it('every fresh league player starts with empty careerStats', () => {
    const league = createLeague({ seed: 'cs-fresh' });
    for (const p of Object.values(league.players)) {
      expect(p.careerStats).toEqual([]);
    }
  });

  it('appends one careerStats entry per active season for top QBs', () => {
    let league = createLeague({ seed: 'cs-qb-multi' });
    // Pick a QB1 from one team and follow them across seasons.
    const team = Object.values(league.teams)[0]!;
    const qb1Id = team.rosterIds.find(
      (id) => league.players[id]!.position === Position.QB,
    )!;

    for (let i = 1; i <= 3; i++) {
      league = simulateSeason(league);
      league = advanceSeason(league);
      const qb = league.players[qb1Id];
      // Some QBs may retire, in which case the test for them stops here.
      if (!qb) break;
      expect(qb.careerStats.length).toBeGreaterThanOrEqual(1);
      // Most-recent entry's seasonNumber matches the season that just
      // wrapped (which is league.seasonNumber - 1 after advancing).
      const last = qb.careerStats[qb.careerStats.length - 1]!;
      expect(last.seasonNumber).toBe(league.seasonNumber - 1);
    }
  });

  it('careerStats only contains entries for seasons with non-zero output', () => {
    const league = runSeasons('cs-no-zero', 3);
    for (const p of Object.values(league.players)) {
      for (const entry of p.careerStats) {
        const recordedSomething =
          entry.passAttempts > 0 ||
          entry.rushingAttempts > 0 ||
          entry.targets > 0 ||
          entry.tackles > 0 ||
          entry.sacks > 0 ||
          entry.interceptions > 0;
        expect(recordedSomething).toBe(true);
      }
    }
  });

  it('careerStats entries are strictly increasing in seasonNumber', () => {
    const league = runSeasons('cs-mono', 5);
    for (const p of Object.values(league.players)) {
      for (let i = 1; i < p.careerStats.length; i++) {
        expect(p.careerStats[i]!.seasonNumber).toBeGreaterThan(
          p.careerStats[i - 1]!.seasonNumber,
        );
      }
    }
  });

  it('snapshotted entry equals the player stat line from the season just played', () => {
    const played = simulateSeason(createLeague({ seed: 'cs-snapshot' }));
    const sStats = seasonStatsForLeague(played);
    const advanced = advanceSeason(played);

    // Sample ~10 players who recorded output and confirm the last
    // careerStats entry matches what the aggregator returned pre-advance.
    let checked = 0;
    for (const [pid, sLine] of sStats) {
      const pAfter = advanced.players[pid];
      // Player may have retired and been removed.
      if (!pAfter) continue;
      const last = pAfter.careerStats[pAfter.careerStats.length - 1]!;
      expect(last.seasonNumber).toBe(played.seasonNumber);
      // Compare the recorded stat fields, ignoring the seasonNumber wrapper.
      const { seasonNumber: _sn, ...rest } = last;
      expect(rest).toEqual(sLine);
      checked++;
      if (checked >= 10) break;
    }
    expect(checked).toBeGreaterThan(0);
  });

  it('rookies generated by retirement start with empty careerStats', () => {
    const played = simulateSeason(createLeague({ seed: 'cs-rookie' }));
    const beforeIds = new Set(Object.keys(played.players));
    const after = advanceSeason(played);
    const newIds = Object.keys(after.players).filter((id) => !beforeIds.has(id));
    expect(newIds.length).toBeGreaterThan(0);
    for (const id of newIds) {
      expect(after.players[id]!.careerStats).toEqual([]);
    }
  });

  it('determinism — same seed produces identical careerStats arrays', () => {
    const a = runSeasons('cs-det', 3);
    const b = runSeasons('cs-det', 3);
    for (const id of Object.keys(a.players)) {
      expect(b.players[id]!.careerStats).toEqual(a.players[id]!.careerStats);
    }
  });

  it('top QB after 5 seasons has plausible career passing yards', () => {
    const league = runSeasons('cs-totals', 5);
    const qbs = Object.values(league.players).filter(
      (p) => p.position === Position.QB && p.careerStats.length >= 3,
    );
    const careerYards = qbs.map((p) =>
      p.careerStats.reduce((s, e) => s + e.passingYards, 0),
    );
    const top = Math.max(...careerYards);
    // Across multiple seasons the top long-tenured QB should be in
    // the 10k-30k career yards range.
    expect(top).toBeGreaterThan(8_000);
    expect(top).toBeLessThan(35_000);
  });
});
